version: "3.3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=dr-trottoir
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: ./startupscript.sh
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      # TODO uit de env file halen? maar hoe?
      - DB_NAME=dr-trottoir
      - DB_USER=postgres
      - DB_PASSWORD=dr-trottoir
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL=example@example.com
      - EMAIL_PASSWORD=example
    depends_on:
      - db
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: run serve
    volumes:
      - ./frontend:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
  docs:
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    environment:
      - GIT_CONFIG_NOSYSTEM=true
    ports:
      - "1313:8080"
