# Generated by Django 4.1.7 on 2023-04-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ronde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureType', models.CharField(choices=[('AR', 'Arrival'), ('ST', 'Storage'), ('DE', 'Departure'), ('EX', 'Extra')], max_length=2)),
                ('image', models.ImageField(upload_to='')),
                ('time', models.DateTimeField()),
                ('remark', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DagPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ronde', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ronde.ronde')),
            ],
        ),
        migrations.CreateModel(
            name='WeekPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoPerBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(default='')),
                ('dagPlanning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.dagplanning')),
            ],
        ),
    ]
