# Generated by Django 4.2 on 2023-04-17 13:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trashtemplates", "0001_initial"),
        ("ronde", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pictureType",
                    models.CharField(
                        choices=[
                            ("AR", "Arrival"),
                            ("ST", "Storage"),
                            ("DE", "Departure"),
                            ("EX", "Extra"),
                        ],
                        max_length=2,
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("time", models.DateTimeField()),
                ("remark", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="DagPlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("NS", "Not started"),
                                ("ST", "Started"),
                                ("FI", "Finished"),
                            ],
                            max_length=2,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "ronde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="ronde.ronde"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("even", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("E", "Eenmalig"),
                            ("V", "Vervangen"),
                            ("A", "Actief"),
                            ("I", "Inactief"),
                        ],
                        max_length=1,
                    ),
                ),
                ("start_hour", models.TimeField()),
                ("end_hour", models.TimeField()),
                ("year", models.IntegerField()),
                ("week", models.IntegerField()),
                (
                    "dag_planningen",
                    models.ManyToManyField(blank=True, to="planning.dagplanning"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ronde.locatieenum",
                    ),
                ),
                ("rondes", models.ManyToManyField(blank=True, to="ronde.ronde")),
            ],
        ),
        migrations.CreateModel(
            name="WeekPlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "student_templates",
                    models.ManyToManyField(blank=True, to="planning.studenttemplate"),
                ),
                (
                    "trash_templates",
                    models.ManyToManyField(
                        blank=True, to="trashtemplates.trashcontainertemplate"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfoPerBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.TextField(default="")),
                ("date", models.DateField()),
                (
                    "dagPlanning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planning.dagplanning",
                    ),
                ),
            ],
        ),
    ]
