# Generated by Django 4.2 on 2023-04-17 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pickupdays", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagplanning",
            name="students",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="dagplanning",
            name="time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pickupdays.pickupday",
            ),
        ),
        migrations.AddField(
            model_name="buildingpicture",
            name="infoPerBuilding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="planning.infoperbuilding",
            ),
        ),
    ]
