# Generated by Django 4.1.7 on 2023-04-14 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dagplanning',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dagplanning',
            name='weekPlanning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning.weekplanning'),
        ),
        migrations.AddField(
            model_name='buildingpicture',
            name='infoPerBuilding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.infoperbuilding'),
        ),
    ]
