# Generated by Django 4.1.7 on 2023-05-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ronde', '0001_initial'),
        ('trashtemplates', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekplanning',
            name='trash_templates',
            field=models.ManyToManyField(blank=True, to='trashtemplates.trashcontainertemplate'),
        ),
        migrations.AddField(
            model_name='studenttemplate',
            name='dag_planningen',
            field=models.ManyToManyField(blank=True, to='planning.dagplanning'),
        ),
        migrations.AddField(
            model_name='studenttemplate',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ronde.locatieenum'),
        ),
        migrations.AddField(
            model_name='studenttemplate',
            name='rondes',
            field=models.ManyToManyField(blank=True, to='ronde.ronde'),
        ),
        migrations.AddField(
            model_name='infoperbuilding',
            name='dagPlanning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.dagplanning'),
        ),
        migrations.AddField(
            model_name='dagplanning',
            name='ronde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ronde.ronde'),
        ),
    ]
