# Generated by Django 4.1.7 on 2023-05-06 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0002_initial'),
        ('pickupdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dagplanning',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dagplanning',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pickupdays.pickupday'),
        ),
        migrations.AddField(
            model_name='buildingpicture',
            name='infoPerBuilding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.infoperbuilding'),
        ),
    ]
