# Generated by Django 4.2 on 2023-05-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_infoperbuilding_building"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dagplanning",
            name="status",
        ),
        migrations.RemoveField(
            model_name="infoperbuilding",
            name="date",
        ),
    ]
