# Generated by Django 4.1.7 on 2023-04-14 13:38

from django.db import migrations, models
import django.db.models.deletion
import ronde.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.TextField()),
                ('ivago_klantnr', models.IntegerField()),
                ('buildingID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocatieEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ronde.models.Manual.upload_to)),
                ('fileType', models.TextField()),
                ('manualStatus', models.TextField(choices=[('Klaar', 'Klaar'), ('Update nodig', 'Update Nodig'), ('Bezig', 'Bezig'), ('Geüpdatet', 'Geupdatet')])),
            ],
        ),
        migrations.CreateModel(
            name='Ronde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('buildings', models.ManyToManyField(to='ronde.building')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ronde.locatieenum', verbose_name='Locatie')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ronde.locatieenum'),
        ),
        migrations.AddField(
            model_name='building',
            name='manual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ronde.manual'),
        ),
    ]
