# Generated by Django 4.1.7 on 2023-05-06 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ronde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='syndicus',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
