# Generated by Django 4.1.7 on 2023-04-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pickupdays', '0001_initial'),
        ('ronde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PM', 'PMD'), ('RE', 'REST'), ('PK', 'PK'), ('GL', 'GLAS'), ('GF', 'GFT')], max_length=2)),
                ('special_actions', models.TextField(blank=True, default='')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ronde.building')),
                ('collection_days', models.ManyToManyField(to='pickupdays.pickupday')),
            ],
        ),
    ]
