# Generated by Django 4.1.7 on 2023-05-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pickupdays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PM', 'PMD'), ('RE', 'REST'), ('PK', 'PK'), ('GL', 'GLAS'), ('GF', 'GFT')], max_length=2)),
                ('collection_day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pickupdays.pickupday')),
            ],
        ),
    ]
