# Generated by Django 4.1.7 on 2023-05-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trashcontainers', '0001_initial'),
        ('ronde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingTrashContainerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ronde.building')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraId',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrashContainerIdWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trashtemplates.extraid')),
                ('trash_container', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trashcontainers.trashcontainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrashContainerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('even', models.BooleanField()),
                ('status', models.CharField(choices=[('E', 'Eenmalig'), ('V', 'Vervangen'), ('A', 'Actief'), ('I', 'Inactief')], max_length=1)),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('buildings', models.ManyToManyField(blank=True, to='trashtemplates.buildingtrashcontainerlist')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ronde.locatieenum')),
                ('trash_containers', models.ManyToManyField(blank=True, to='trashtemplates.trashcontaineridwrapper')),
            ],
        ),
        migrations.AddField(
            model_name='buildingtrashcontainerlist',
            name='trash_ids',
            field=models.ManyToManyField(to='trashtemplates.extraid'),
        ),
    ]
