name: backend-tests
run-name: backend-tests
on: [push]
jobs:
  Backend-linter-and-tests:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
        
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
        working-directory: ./backend
      - name: Run Tests
        run: |
          flake8 .
          #python manage.py test
        working-directory: ./backend
