name: frontend-tests
run-name: frontend-tests
on: [push]
jobs:
  Frontend-tests:
    runs-on: self-hosted
    environment: vue tests
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Empty EchoFetch directory
        run: |
          rm -rf EchoFetch
        working-directory: ./frontend/src/api
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup EchoFetch
        run: |
          npm install
          npm run build
        working-directory: ./frontend/src/api/EchoFetch
      - name: Install Dependencies
        run: |
          npm install --force
        working-directory: ./frontend
      - name: Run Tests
        run: |
          npm run test:unit
        working-directory: ./frontend